version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    # Add reviewers
    reviewers:
      - "albertmeronyo"
      - "c-martinez"
