sudo: false
language: python
cache: pip
python: 3.5

before_install:
  - source .travis/before_install.sh
install:
  - source .travis/install.sh
# command to run tests
script:
  - source .travis/run.sh

jobs:
  include:
    - stage: Tests
      os: linux
      python: '2.7'
    - stage: Tests
      os: linux
      python: '3.6'
    - stage: Tests
      os: osx
      language: objective-c
      env: PYENV_VERSION=2.7.12
    - stage: Tests
      os: osx
      language: objective-c
      env: PYENV_VERSION=3.5.2
      # command to install dependencies
    - stage: deploy
      script: skip
      # deploy automatically to pypi
      deploy:
        provider: pypi
        server: https://test.pypi.org/legacy/
        user: nlesc
        distributions: sdist bdist_wheel
        password:
          secure: h3xI8W2eEa2QpmyGdc5uT4sS+pPVqEGArKFAOhbEbVjAtPoQJ2cIn8KsdsiA4goPdnBjkn1lzMuWvC1Rppgb+MkfbjzeghGySH61PEj01J+yJ4gZtQE12TS9Wrwtm/+SBKHOR5CGVlpVMr31O2kH09pFQpVKqmOYZLVDaKJJLs0+c/snhHllg0v0g6YhAsnL3w6uS3lfWQ3rPSR3OXbkdctGAjId6n8gnmvrgSBY/SBjA2a+iNcCke9AuzovBBPOozkPq4yBe9uhP8a1GpsF1VGqU0II0YSEz70IUDI+QPVAaoSFtr8xdxrqv+7BDRF6ZIYVrufQzJ0a9U7SHzB+WcTVN/D47Zg7XNslgSByi4ULr4GPUPB+DUjxICgrjHxOEDX8kx8cw+tTUSKqcThHNUK2p958YeAaUfEtr9vNj828o7/xp9DkYMCsnVSDROguMj/stXJOC7gn1WK8D96IentZiGmhIGfEmz8jSrOyqxzn2omkzfjdjaXduPVG+0BaaWQgOzAns+y8Opl4Q3qmTSxIt17QAO0COFFY5aa1qjQVXS1WBO72vrrAbSFKND9JiEG2HuX3DUb6mGH7raZhR5TUc4xOnlNIpndW2+W95DtkUrzJvJk3nTYFA96dNlWad2pBHp6wH8rxfvb8AGCLgBF1Sm6SDkXob5VLBMD3jTE=
        on:
          tags: true
          branch: master
