version: '2'
services:
  grlc:
    image: 1cc74dd0379e
    build: ./docker-build
    ports:
     - "8001:80"
    environment:
     - DEBUG=true
     - USERMAP_GID=1000
     - USERMAP_UID=1000
    volumes:
     - /home/amp/src/grlc:/home/grlc/grlc
