version: 1

update_configs:
  - package_manager: "python"
    directory: "/python/helpers"
    update_schedule: "monthly"
    target_branch: "dev"
    default_reviewers:
      - "albertmeronyo"
      - "c-martinez"
